name = "dirtree"
version = "1.0.6"
description = "A directory tree abstraction including a pretty-printer"
licences = ["Apache-2.0"]
repository = { type = "github", user = "vistuleB", repo = "dirtree" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
